-- Add E911 address fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS e911_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS e911_street TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS e911_city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS e911_state TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS e911_zip TEXT;

-- Add 2FA fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_factor_otp TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_factor_otp_expires_at TIMESTAMP;
